# Generated by Django 5.0.3 on 2026-02-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMLDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('risk_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alerts', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CreditAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(max_length=100)),
                ('risk_score', models.FloatField()),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('MANUAL_REVIEW', 'Manual Review')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alerts', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=100)),
                ('fraud_risk', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alerts', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MarketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('manipulation_risk', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alerts', models.JSONField(default=list)),
            ],
        ),
    ]
