# Generated by Django 4.2.28 on 2026-02-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amldetection',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='amldetection',
            name='receiver_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amldetection',
            name='sender_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='claim_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='policy_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketalert',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marketalert',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
