FROM python:3.9-slim

WORKDIR /app

RUN pip install streamlit pandas psycopg2-binary plotly sqlalchemy

CMD ["streamlit", "run", "src/dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
